// Generated by Wrangler on Sun Jul 21 2024 23:10:23 GMT+0200 (Central European Summer Time)
// by running `wrangler types`

interface Env {
	KV_LINKS: KVNamespace;
	DEBUG_MODE: true;
	CFG_SITE_HTTP_ORIGIN: "https://kes.im";
	CFG_SITE_HTTP_HOSTNAME: "kes.im";
	CFG_SITE_HTTP_API_HOSTNAME: "api.kes.im";
	CFG_RANDOM_SLUG_LENGTH: 5;
	CFG_MIN_SLUG_LENGTH: 3;
	CFG_MAX_SLUG_LENGTH: 64;
	CFG_MIN_URL_LENGTH: 10;
	CFG_MAX_URL_LENGTH: 2048;
	CFG_DEFAULT_CACHE_AGE: 3600;
	CFG_STATIC_CACHE_AGE: 86400;
	CFG_REDIRECT_CACHE_AGE: 31536000;
	CF_STATIC_ASSET_TTL: 172800;
	CF_TURNSTILE_VERIFY_URL: "https://challenges.cloudflare.com/turnstile/v0/siteverify";
	CF_KV_CACHE_TTL: 864000;
	D1_LINKS: D1Database;
	API_RATE_LIMITER: RateLimit;
}
